# Generated by Django 5.0.3 on 2024-03-08 09:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0009_project_done_at_alter_project_deadline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="task_list",
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="core.project",
            ),
        ),
    ]
