# Generated by Django 5.0.3 on 2024-03-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
