# Generated by Django 5.0.3 on 2024-03-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_project_created_at_alter_task_created_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="worker",
            name="unique_username",
        ),
    ]
